use super::harness::ok_json;

const SKILL: &str = include_str!("../../work/generated/exa-agent-cli/SKILL.md");

#[test]
fn generated_skill_is_the_robot_docs_golden() {
    let guide = ok_json(&["robot-docs", "guide", "--compact"]);
    let examples = ok_json(&["robot-docs", "examples", "--task", "search", "--compact"]);
    let mut expected = String::from(
        "---\nname: exa-agent-cli\ndescription: Use the exa-agent CLI for Exa search, contents, answer, context, similar, Websets, monitors, and agent workflows.\n---\n\n# exa-agent CLI skill\n\nGenerated by `cargo xtask generate-skill`; do not edit by hand.\n\n## Guidance\n",
    );
    for line in guide["guidance"].as_array().expect("guidance array") {
        expected.push_str("- ");
        expected.push_str(line.as_str().expect("guidance string"));
        expected.push('\n');
    }
    expected.push_str("\n## Offline examples\n\n");
    for line in examples["examples"].as_array().expect("examples array") {
        expected.push_str("```sh\n");
        expected.push_str(line.as_str().expect("example string"));
        expected.push_str("\n```\n");
    }
    assert_eq!(SKILL, expected);
}
