use super::harness::ok_json;

const SKILL: &str = include_str!("../../skills/exa-agent-cli/SKILL.md");

#[test]
fn generated_skill_is_the_robot_docs_golden() {
    let guide = ok_json(&["robot-docs", "guide", "--compact"]);
    let examples = ok_json(&["robot-docs", "examples", "--task", "search", "--compact"]);
    let mut expected = String::from(
        "---\nname: exa-agent-cli\ndescription: \"Exa via the exa-agent CLI: web search for sources, full page text from a URL, a cited answer, similar pages, Websets, monitors, agent runs, batches, and the no-spend credit and auth preflight before a research task that depends on Exa.\"\n---\n\n# exa-agent CLI\n\n`exa-agent` is a non-interactive CLI for the full Exa API.\nStructured successes are JSON envelopes with `ok`, `data`, `warnings`, and `nextActions`; errors are JSON on stderr with a stable `error.code`.\n`exa-agent robot-docs guide|examples|errors` and `exa-agent capabilities <command>` expose this playbook offline.\n\n<!-- Generated by cargo xtask generate-skill from exa-agent robot-docs guide; edit src/lib.rs GUIDE_SECTIONS, then regenerate. -->\n",
    );
    for section in guide["sections"].as_array().expect("sections array") {
        expected.push_str("\n## ");
        expected.push_str(section["title"].as_str().expect("section title"));
        expected.push('\n');
        for rule in section["rules"].as_array().expect("section rules array") {
            expected.push_str("- ");
            expected.push_str(rule.as_str().expect("rule string"));
            expected.push('\n');
        }
    }
    expected.push_str("\n## Offline examples\n\n```sh\n");
    for line in examples["examples"].as_array().expect("examples array") {
        expected.push_str(line.as_str().expect("example string"));
        expected.push('\n');
    }
    expected.push_str("```\n");
    assert_eq!(SKILL, expected);
    for required in [
        "Use `--fresh` for latest or current material",
        "--snapshot-as-of",
        "file's root is the former `data` object",
        "`--output FILE` keeps the full envelope in a file",
        "`--max-output-bytes 0` disables spilling",
    ] {
        assert!(
            SKILL.contains(required),
            "missing skill guidance: {required}"
        );
    }
}
