//! Build/dev tooling for exa-agent-cli. Run as `cargo xtask <cmd>`.
//!
//! Implemented: `vendor-spec [--check]`, `ci`, `phase-gate N`. The registry itself is
//! generated by `build.rs` at build time (D9), so `generate-registry` just triggers a build.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{anyhow, bail, Context, Result};

const EXA_SPEC_URL: &str = "https://exa.ai/docs/exa-spec.json";
const ADMIN_SPEC_URL: &str = "https://exa.ai/docs/team-management-spec.yaml";

const EXA_SPEC: &str = "openapi/exa-openapi.json";
const ADMIN_SPEC: &str = "openapi/team-management.json";
const OVERLAY: &str = "openapi/overlay.toml";

// Verified spec identity (D22, 2026-06-29). The Phase-1 goldens freeze these.
const EXA_TITLE: &str = "Exa Public API";
const EXA_VERSION: &str = "2.0.0";
const ADMIN_TITLE: &str = "Team Management API";
const ADMIN_VERSION: &str = "1.0.0";

fn main() -> Result<()> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let cmd = args.first().map(String::as_str).unwrap_or("help");
    let rest = &args[args.len().min(1)..];
    match cmd {
        "vendor-spec" => vendor_spec(rest.contains(&"--check".to_string())),
        "generate-registry" => generate_registry(),
        "ci" => ci(),
        "phase-gate" => phase_gate(rest.first().map(String::as_str)),
        "help" | "--help" | "-h" => {
            print_help();
            Ok(())
        }
        other => {
            print_help();
            bail!("unknown xtask command: {other}");
        }
    }
}

fn print_help() {
    eprintln!(
        "xtask commands:\n  \
         vendor-spec [--check]   fetch/verify the vendored OpenAPI specs (Phase-0 gate)\n  \
         generate-registry       trigger a build (registry is codegen'd by build.rs)\n  \
         ci                       offline gate: fmt --check, clippy -D warnings, test\n  \
         phase-gate N             run the tests/snapshots required for Phase N"
    );
}

fn repo_root() -> Result<PathBuf> {
    // xtask runs from the workspace root under `cargo xtask`; fall back to CARGO_MANIFEST_DIR/..
    let out = Command::new("git")
        .args(["rev-parse", "--show-toplevel"])
        .output();
    if let Ok(o) = out {
        if o.status.success() {
            let p = String::from_utf8_lossy(&o.stdout).trim().to_string();
            if !p.is_empty() {
                return Ok(PathBuf::from(p));
            }
        }
    }
    Ok(std::env::current_dir()?)
}

fn vendor_spec(check_only: bool) -> Result<()> {
    let root = repo_root()?;
    if check_only {
        verify_spec(&root.join(EXA_SPEC), EXA_TITLE, EXA_VERSION)?;
        verify_spec(&root.join(ADMIN_SPEC), ADMIN_TITLE, ADMIN_VERSION)?;
        verify_overlay(&root)?;
        println!("vendor-spec --check: OK (specs parse, identity verified, overlay consistent)");
        return Ok(());
    }

    // Live re-vendor. The Exa public spec is served as JSON; the admin spec as YAML, so it is
    // normalized to JSON via ruby (no YAML parser ships in the binary, D21).
    fetch_json(EXA_SPEC_URL, &root.join(EXA_SPEC))?;
    fetch_yaml_as_json(ADMIN_SPEC_URL, &root.join(ADMIN_SPEC))?;
    verify_spec(&root.join(EXA_SPEC), EXA_TITLE, EXA_VERSION)?;
    verify_spec(&root.join(ADMIN_SPEC), ADMIN_TITLE, ADMIN_VERSION)?;
    println!("vendor-spec: re-vendored and verified {EXA_SPEC} + {ADMIN_SPEC}");
    Ok(())
}

fn fetch_json(url: &str, dest: &Path) -> Result<()> {
    let out = Command::new("curl")
        .args(["-sS", "-L", "--fail", "--max-time", "60", url])
        .output()
        .context("run curl")?;
    if !out.status.success() {
        bail!(
            "curl failed for {url}: {}",
            String::from_utf8_lossy(&out.stderr)
        );
    }
    // Round-trip through serde_json to normalize whitespace deterministically.
    let v: serde_json::Value = serde_json::from_slice(&out.stdout).context("parse fetched JSON")?;
    std::fs::write(dest, serde_json::to_string_pretty(&v)? + "\n")?;
    Ok(())
}

fn fetch_yaml_as_json(url: &str, dest: &Path) -> Result<()> {
    let script = format!(
        "require 'yaml'; require 'json'; require 'open-uri'; \
         d = YAML.safe_load(URI.open({url:?}).read, aliases: true); \
         File.write({dest:?}, JSON.pretty_generate(d) + \"\\n\")",
        url = url,
        dest = dest.to_string_lossy(),
    );
    let out = Command::new("ruby")
        .args(["-e", &script])
        .output()
        .context("run ruby (YAML->JSON conversion needs ruby on PATH)")?;
    if !out.status.success() {
        bail!(
            "ruby YAML->JSON failed: {}",
            String::from_utf8_lossy(&out.stderr)
        );
    }
    Ok(())
}

fn verify_spec(path: &Path, want_title: &str, want_version: &str) -> Result<()> {
    let bytes = std::fs::read(path).with_context(|| format!("read {}", path.display()))?;
    let v: serde_json::Value =
        serde_json::from_slice(&bytes).with_context(|| format!("parse {}", path.display()))?;
    let title = v
        .pointer("/info/title")
        .and_then(|x| x.as_str())
        .unwrap_or("");
    let version = v
        .pointer("/info/version")
        .and_then(|x| x.as_str())
        .unwrap_or("");
    if title != want_title || version != want_version {
        bail!(
            "{}: identity mismatch — got {title:?} {version:?}, want {want_title:?} {want_version:?}",
            path.display()
        );
    }
    Ok(())
}

/// Every overlay operation must resolve to a spec op (or be overlay-defined). This is the
/// offline half of the registry-consistency guarantee (arch §3).
fn verify_overlay(root: &Path) -> Result<()> {
    let overlay: toml::Value = toml::from_str(&std::fs::read_to_string(root.join(OVERLAY))?)
        .context("parse overlay.toml")?;
    let spec_ops = collect_op_ids(&root.join(EXA_SPEC))?
        .into_iter()
        .chain(collect_op_ids(&root.join(ADMIN_SPEC))?)
        .collect::<BTreeMap<_, _>>();

    let ops = overlay
        .get("operations")
        .and_then(|x| x.as_table())
        .ok_or_else(|| anyhow!("overlay.toml has no [operations] table"))?;

    let mut problems = Vec::new();
    for (oid, meta) in ops {
        let defined = meta
            .get("defined_by_overlay")
            .and_then(|x| x.as_bool())
            .unwrap_or(false);
        if !defined && !spec_ops.contains_key(oid.as_str()) {
            problems.push(format!("overlay op {oid:?} not found in any vendored spec"));
        }
        if meta.get("cli_path").and_then(|x| x.as_str()).is_none() {
            problems.push(format!("overlay op {oid:?} missing cli_path"));
        }
    }
    if !problems.is_empty() {
        bail!("overlay inconsistencies:\n  {}", problems.join("\n  "));
    }
    Ok(())
}

fn collect_op_ids(path: &Path) -> Result<Vec<(String, ())>> {
    let v: serde_json::Value = serde_json::from_slice(&std::fs::read(path)?)?;
    let mut out = Vec::new();
    if let Some(paths) = v.get("paths").and_then(|p| p.as_object()) {
        for methods in paths.values() {
            let Some(methods) = methods.as_object() else {
                continue;
            };
            for op in methods.values() {
                if let Some(oid) = op.get("operationId").and_then(|x| x.as_str()) {
                    out.push((oid.to_string(), ()));
                }
            }
        }
    }
    Ok(out)
}

fn generate_registry() -> Result<()> {
    // The registry is emitted by build.rs into OUT_DIR; a build regenerates it reproducibly.
    run("cargo", &["build", "--quiet"])?;
    println!("generate-registry: built (registry.rs emitted to OUT_DIR by build.rs)");
    Ok(())
}

fn ci() -> Result<()> {
    run("cargo", &["fmt", "--all", "--", "--check"])?;
    run(
        "cargo",
        &[
            "clippy",
            "--all-targets",
            "--all-features",
            "--",
            "-D",
            "warnings",
        ],
    )?;
    run("cargo", &["test", "--workspace", "--locked"])?;
    println!("ci: OK");
    Ok(())
}

fn phase_gate(n: Option<&str>) -> Result<()> {
    let n = n.unwrap_or("1");
    run("cargo", &["test", "--workspace", "--locked"])?;
    if matches!(n, "1" | "2") {
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "capabilities",
                "--compact",
            ],
            "exa.cli.capabilities.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "schema",
                "list",
                "--compact",
            ],
            "exa.cli.schema_list.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "schema",
                "show",
                "search",
                "--compact",
            ],
            "exa.cli.schema_show.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "schema",
                "refresh",
                "--check",
                "--compact",
            ],
            "exa.cli.schema_refresh.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "robot-docs",
                "guide",
                "--compact",
            ],
            "exa.cli.robot_docs.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "raw",
                "GET",
                "/search",
                "--body",
                "{\"query\":\"agents\"}",
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "search",
                "agents",
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
    }
    if n == "2" {
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "contents",
                "https://example.com",
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "contents",
                "--ids",
                "doc-id-1",
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "answer",
                "What is Exa?",
                "--text",
                "--stream",
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "context",
                "rust async patterns",
                "--tokens",
                "1000",
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "similar",
                "https://exa.ai",
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "team",
                "info",
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "research",
                "create",
                "legacy topic",
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
        run(
            "cargo",
            &[
                "test",
                "--quiet",
                "--test",
                "transport",
                "streaming_ndjson_shape_from_canned_sse",
                "--",
                "--exact",
            ],
        )?;
    }
    if n == "3" {
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "agent",
                "run",
                "find eval tools",
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "agent",
                "runs",
                "create",
                "find eval tools",
                "--output-schema",
                "{\"type\":\"object\"}",
                "--input-row",
                "{\"company\":\"OpenAI\"}",
                "--previous-run-id",
                "agent_run_prev",
                "--effort",
                "medium",
                "--data-source",
                "similarweb",
                "--metadata",
                "{\"ticket\":\"T1\"}",
                "--stream",
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "agent",
                "runs",
                "list",
                "--limit",
                "5",
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "agent",
                "runs",
                "get",
                "agent_run_abc",
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "agent",
                "runs",
                "events",
                "agent_run_abc",
                "--stream",
                "--last-event-id",
                "evt_1",
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "agent",
                "runs",
                "cancel",
                "agent_run_abc",
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "agent",
                "runs",
                "delete",
                "agent_run_abc",
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
        run(
            "cargo",
            &[
                "test",
                "--quiet",
                "--lib",
                "tests::golden_pending_run_record",
                "--",
                "--exact",
            ],
        )?;
        run(
            "cargo",
            &[
                "test",
                "--quiet",
                "--test",
                "cli",
                "golden_paginated_all_ndjson",
                "--",
                "--exact",
            ],
        )?;
        run(
            "cargo",
            &[
                "test",
                "--quiet",
                "--test",
                "cli",
                "sse_sigint_stalled_stream_exits_12_with_last_event_id",
                "--",
                "--exact",
            ],
        )?;
    }
    if n == "4" {
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "monitor",
                "create",
                "--name",
                "daily",
                "--query",
                "AI news",
                "--schedule",
                "6h",
                "--webhook-url",
                "https://example.com/hook",
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "monitor",
                "list",
                "--status",
                "active",
                "--metadata",
                "owner=ops",
                "--limit",
                "5",
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "monitor",
                "get",
                "mon_abc",
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "monitor",
                "batch",
                "--body",
                r#"{"action":"pause","filter":{"status":"active"}}"#,
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
        run_json(
            "cargo",
            &[
                "run",
                "--quiet",
                "--bin",
                "exa-agent",
                "--",
                "monitor",
                "runs",
                "list",
                "mon_abc",
                "--dry-run",
                "--print-request",
                "--compact",
            ],
            "exa.cli.response.v1",
        )?;
        run(
            "cargo",
            &[
                "test",
                "--quiet",
                "--test",
                "cli",
                "monitor",
                "--",
                "--nocapture",
            ],
        )?;
    }
    println!("phase-gate {n}: OK");
    Ok(())
}

fn run_json(cmd: &str, args: &[&str], expected_schema: &str) -> Result<()> {
    eprintln!("$ {cmd} {}", args.join(" "));
    let output = Command::new(cmd)
        .args(args)
        .output()
        .with_context(|| format!("spawn {cmd}"))?;
    if !output.status.success() {
        bail!(
            "{cmd} {} failed ({})\nstdout:\n{}\nstderr:\n{}",
            args.join(" "),
            output.status,
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
    let value: serde_json::Value = serde_json::from_slice(&output.stdout).with_context(|| {
        format!(
            "{cmd} {} did not emit JSON on stdout:\n{}",
            args.join(" "),
            String::from_utf8_lossy(&output.stdout)
        )
    })?;
    let schema = value
        .get("schema")
        .and_then(serde_json::Value::as_str)
        .unwrap_or("");
    if schema != expected_schema {
        bail!(
            "{cmd} {} emitted schema `{schema}`, expected `{expected_schema}`",
            args.join(" ")
        );
    }
    Ok(())
}

fn run(cmd: &str, args: &[&str]) -> Result<()> {
    eprintln!("$ {cmd} {}", args.join(" "));
    let status = Command::new(cmd)
        .args(args)
        .status()
        .with_context(|| format!("spawn {cmd}"))?;
    if !status.success() {
        bail!("{cmd} {} failed ({status})", args.join(" "));
    }
    Ok(())
}
